'use strict';
const STORAGE_KEY='conversation-course-v1';
const TASKS=['recall','learn','quiz','speak'];
let lessons=[], selected=1, state=readState(), timerId=null, remaining=120;
const $=id=>document.getElementById(id);
function readState(){try{const v=JSON.parse(localStorage.getItem(STORAGE_KEY));return v&&typeof v==='object'?v:{startDate:localDate(),days:{}}}catch{return {startDate:localDate(),days:{}}}}
function localDate(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function save(){try{localStorage.setItem(STORAGE_KEY,JSON.stringify(state))}catch{}}
function dayData(n){state.days ||= {};return state.days[n] ||= {tasks:{},answers:{},notes:''}}
function completed(n){return TASKS.every(t=>dayData(n).tasks[t])}
function txt(id,value){$(id).textContent=value}
function el(tag,cls,value){const node=document.createElement(tag);if(cls)node.className=cls;if(value!==undefined)node.textContent=value;return node}
function dateAt(n){if(!/^\d{4}-\d{2}-\d{2}$/.test(state.startDate||''))return '';const [y,m,d]=state.startDate.split('-').map(Number);const date=new Date(y,m-1,d+n-1);return new Intl.DateTimeFormat(undefined,{month:'short',day:'numeric'}).format(date)}
function currentDay(){if(!state.startDate)return 1;const [y,m,d]=state.startDate.split('-').map(Number);const now=new Date();const diff=Math.floor((Date.UTC(now.getFullYear(),now.getMonth(),now.getDate())-Date.UTC(y,m-1,d))/86400000);return Math.min(30,Math.max(1,diff+1))}
function refreshNav(){const count=lessons.filter(l=>completed(l.day)).length;txt('progress-count',`${count} / 30`);$('progress-fill').style.width=`${count/30*100}%`;$('course-progress').setAttribute('aria-valuenow',count);txt('today-label',`Suggested today: Day ${currentDay()}`);for(const container of [$('day-list'),$('mobile-menu')]){container.replaceChildren();if(container.id==='mobile-menu'){const dateBox=document.querySelector('.date-box').cloneNode(true);dateBox.querySelector('input').id='mobile-start-date';dateBox.querySelector('label').htmlFor='mobile-start-date';dateBox.querySelector('input').value=state.startDate||'';dateBox.querySelector('input').addEventListener('change',e=>setStart(e.target.value));container.append(dateBox)}lessons.forEach(l=>{const b=el('button','day-link'+(l.day===selected?' active':'')+(completed(l.day)?' done':''));b.type='button';b.setAttribute('aria-current',l.day===selected?'page':'false');b.append(el('span','day-number',String(l.day).padStart(2,'0')),el('span','day-name',l.title));if(completed(l.day))b.append(el('span','check','✓'));b.addEventListener('click',()=>show(l.day));container.append(b)});if(container.id==='mobile-menu'){const a=el('a','book-link','↓ Download full coursebook (.md)');a.href='COURSEBOOK.md';a.download='';container.append(a)}}}
function setStart(v){state.startDate=v||localDate();save();$('start-date').value=state.startDate;refreshNav();txt('scheduled-date',dateAt(selected))}
function refreshTasks(){const data=dayData(selected);const steps=$('routine-steps');steps.replaceChildren();const labels={recall:selected===1?'Introduce yourself':'Recall yesterday',learn:'Read and repeat',quiz:'Check answers',speak:'Speak and reflect'};TASKS.forEach((t,i)=>{const b=el('button','step'+(data.tasks[t]?' done':'')+(t==='quiz'?' locked':''));b.type='button';b.append(el('span','step-icon',data.tasks[t]?'✓':String(i+1)),el('span','',labels[t]));if(t==='quiz'){b.title='Complete all four quiz answers to mark this step';b.addEventListener('click',()=>$('quiz-card').scrollIntoView({behavior:'smooth'}))}else{b.setAttribute('aria-pressed',!!data.tasks[t]);b.addEventListener('click',()=>toggle(t))}steps.append(b)});txt('day-progress',`${TASKS.filter(t=>data.tasks[t]).length} of 4 steps`);document.querySelectorAll('.task-button').forEach(b=>{const done=!!data.tasks[b.dataset.task];b.classList.toggle('done',done);b.textContent=done?'✓ Done · click to undo':b.dataset.task==='learn'?'Mark learning done':'Mark speaking done'})}
function toggle(t){const d=dayData(selected);d.tasks[t]=!d.tasks[t];save();refreshTasks();refreshNav()}
function renderQuiz(l){const list=$('quiz-list');list.replaceChildren();const d=dayData(l.day);if(d.tasks.quiz&&!l.quiz.every((q,i)=>d.answers[i]===q.answer)){d.tasks.quiz=false;save();}l.quiz.forEach((q,i)=>{const wrap=el('div','question');const fs=el('fieldset');fs.append(el('legend','',`${i+1}. ${q.stem}`));q.options.forEach((option,j)=>{const label=el('label','option');const input=el('input');input.type='radio';input.name=`q${i}`;input.value=String(j);input.checked=d.answers[i]===j;input.addEventListener('change',()=>{d.answers[i]=j;d.tasks.quiz=false;save();refreshTasks();refreshNav();const old=wrap.querySelector('.feedback');if(old)old.remove();txt('quiz-result','')});label.append(input,el('span','',option));fs.append(label)});wrap.append(fs);list.append(wrap)});txt('quiz-result',d.tasks.quiz?'✓ All four questions completed. You can revisit them.':'')}
function checkQuiz(e){e.preventDefault();const l=lessons[selected-1],d=dayData(selected);let correct=0;document.querySelectorAll('.question').forEach((wrap,i)=>{const q=l.quiz[i],old=wrap.querySelector('.feedback');if(old)old.remove();const chosen=wrap.querySelector('input:checked');const good=chosen&&Number(chosen.value)===q.answer;if(good)correct++;wrap.append(el('p',`feedback ${good?'good':'bad'}`,chosen?`${good?'Correct.':'Try again.'} ${q.explanation}`:'Select an answer to continue.'))});if(correct===l.quiz.length){d.tasks.quiz=true;txt('quiz-result','✓ All four correct — quiz step complete.')}else{d.tasks.quiz=false;txt('quiz-result',`${correct} of ${l.quiz.length} correct. Review the feedback and try again.`)}save();refreshTasks();refreshNav()}
function stopTimer(){if(timerId){clearInterval(timerId);timerId=null}remaining=120;txt('timer-display','02:00');txt('timer-button','Start 2-minute timer')}
function renderTimer(){const mm=String(Math.floor(remaining/60)).padStart(2,'0'),ss=String(remaining%60).padStart(2,'0');txt('timer-display',`${mm}:${ss}`)}
function dialogueLines(lines){return lines.map(s=>{const p=el('p'),speaker=el('span','speaker',s.slice(0,2)),line=el('span','',s.slice(3));p.append(speaker,line);return p})}
function renderExtras(l){const families=$('phrase-families');families.replaceChildren(...l.phraseFamilies.map(f=>{const box=el('div','phrase-family');box.append(el('strong','',f.label));const ul=el('ul','');ul.append(...f.options.map(p=>el('li','',p)));box.append(ul);return box}));const scenes=$('extra-dialogues');scenes.replaceChildren(...l.extraDialogues.flatMap(scene=>{const label=el('div','scene-label',scene.label),body=el('div','dialogue');body.append(...dialogueLines(scene.lines));return [label,body]}));$('discussion-prompts').replaceChildren(...l.discussion.map(p=>el('li','',p)))}
function show(n){if(!lessons.length)return;selected=Math.min(30,Math.max(1,n));stopTimer();const l=lessons[selected-1],d=dayData(selected);history.replaceState(null,'',`#day-${selected}`);txt('day-kicker',`DAY ${String(selected).padStart(2,'0')} / 30`);txt('scheduled-date',dateAt(selected));txt('lesson-title',l.title);txt('lesson-theme',l.theme);txt('lesson-objective',l.objective);txt('focus',`Language focus: ${l.focus}`);txt('teaching',l.teaching);txt('usage',l.usage);$('phrases').replaceChildren(...l.phrases.map(p=>el('li','',p)));$('dialogue').replaceChildren(...dialogueLines(l.dialogue));renderExtras(l);txt('reflection-prompt',l.reflection);txt('roleplay-prompt',l.roleplay);$('notes').value=d.notes||'';renderQuiz(l);refreshTasks();refreshNav();$('prev-day').disabled=selected===1;$('next-day').disabled=selected===30;$('mobile-menu').hidden=true;$('menu-toggle').setAttribute('aria-expanded','false');document.title=`Day ${selected}: ${l.title} · 30 Days of Conversation`;window.scrollTo({top:0,behavior:'instant'})}
$('start-date').addEventListener('change',e=>setStart(e.target.value));$('quiz-form').addEventListener('submit',checkQuiz);document.querySelectorAll('.task-button').forEach(b=>b.addEventListener('click',()=>toggle(b.dataset.task)));$('notes').addEventListener('input',e=>{dayData(selected).notes=e.target.value;save()});$('prev-day').addEventListener('click',()=>show(selected-1));$('next-day').addEventListener('click',()=>show(selected+1));$('menu-toggle').addEventListener('click',()=>{const menu=$('mobile-menu');menu.hidden=!menu.hidden;$('menu-toggle').setAttribute('aria-expanded',String(!menu.hidden))});$('timer-button').addEventListener('click',()=>{if(timerId){clearInterval(timerId);timerId=null;txt('timer-button','Resume timer');return}if(remaining===0)remaining=120;txt('timer-button','Pause timer');timerId=setInterval(()=>{remaining--;renderTimer();if(remaining<=0){clearInterval(timerId);timerId=null;txt('timer-button','Start again');txt('timer-display','Done!')}},1000)});$('timer-reset').addEventListener('click',stopTimer);window.addEventListener('hashchange',()=>{const n=Number(location.hash.match(/^#day-(\d+)$/)?.[1]);if(n>=1&&n<=30&&n!==selected)show(n)});
fetch('lessons.json').then(r=>{if(!r.ok)throw new Error('Could not load lesson data');return r.json()}).then(data=>{lessons=data;for(const l of lessons){const d=state.days?.[l.day];if(d?.tasks?.quiz&&!l.quiz.every((q,i)=>d.answers?.[i]===q.answer))d.tasks.quiz=false}state.startDate ||= localDate();$('start-date').value=state.startDate;save();$('loading').hidden=true;$('content').hidden=false;const n=Number(location.hash.match(/^#day-(\d+)$/)?.[1]);show(n>=1&&n<=30?n:currentDay())}).catch(()=>{$('loading').textContent='Lessons could not load. Refresh the page or check that all project files are together.'});
