from pathlib import Path
import re,json
from extra_content import enrich
root=Path(__file__).parent
plan=(root/'ORIGINAL_30_DAY_PLAN.txt').read_text()
sections=re.split(r'(?=DAY \d+ - )',plan)[1:]
# Each record: objective | language focus | teaching note | model exchange (A/B separated by /) | usage note | question 1: stem ~ options separated by ; ~ correct index ~ explanation | question 2 | open question | role-play task
raw='''
Introduce yourself and keep a first meeting going|Open questions and short answers|Use “What do you do?” for work or study. “Where are you from?” asks about origin; “Where do you live?” asks about your current home. After answering, return the question.|A: Hi, I’m Maya. Is this your first time here? / B: Yes, it is. I’m Sam. Nice to meet you. / A: Nice to meet you too. Where are you from? / B: I’m from Recife, but I live here now. How about you?|A friendly follow-up (“How about you?”) prevents the conversation from ending after one answer.|Which question asks about a person's current home?~Where do you live?;Where are you from?;What's your name?~0~“Live” points to the current place.|Choose the natural reply to “Nice to meet you.”~Nice to meet you too.;I am meet.;From my city.~0~Return the greeting with “too.”|How would you introduce yourself at a community event? Ask two different follow-up questions.|You meet a new classmate. Exchange names, hometowns, and what you do; each person asks a follow-up.
Describe relationships clearly and respectfully|Present simple for facts; adjectives with examples|“She’s thoughtful” is stronger when followed by evidence: “She checks in when I’m having a hard week.” “We get along” means you have a good relationship.|A: Do you have any siblings? / B: Yes, an older brother. He lives nearby. / A: Are you two close? / B: We are. We talk most weekends, although we have different interests.|Ask about family with care: some people prefer to discuss friends or chosen family instead.|Which phrase means “have a good relationship”?~Get along;Get around;Get over~0~“Get along” describes a positive relationship.|Which sentence adds a supporting example?~My friend is kind because she helps new students.;My friend is kind.;Friend kind helping.~0~Specific actions make descriptions clearer.|Who is important to you? Describe their personality and one example.|Introduce someone important to you to a new friend; describe how you met and what you enjoy together.
Talk about habits and compare days|Frequency adverbs and time expressions|Place “usually,” “often,” and “sometimes” before the main verb (“I usually cook”) but after “be” (“I’m usually home”). Use “on weekdays” for a repeating pattern.|A: What does a typical weekday look like for you? / B: I usually start work at nine, then take a break around noon. / A: Do you do the same thing on weekends? / B: Not really. I tend to sleep later and meet friends.|“It depends on the day” is a useful honest answer when your schedule changes.|Which is natural?~I usually eat breakfast at eight.;I eat usually breakfast at eight.;Usually I am eat breakfast.~0~Frequency adverbs normally precede the main verb.|Choose the natural phrase for a repeated weekday habit.~On weekdays I take the bus.;At weekday I take bus.;In weekdays bus take.~0~“On weekdays” names the recurring days.|Walk through your morning in order. What changes on weekends?|Ask a partner about their weekday and weekend routines; find two similarities and one difference.
Share interests and invite participation|“Be into” and invitations with “Would you like”|“I’m into photography” sounds conversational. Ask “How did you get into it?” to invite a story. For a polite invitation, use “Would you like to join me?”|A: What do you do for fun? / B: I’m into hiking, especially short trails near town. / A: How did you get into that? / B: A friend invited me last year. Would you like to join us sometime?|Give a brief description of what the activity involves, especially if your listener is new to it.|What does “I’m into painting” mean?~I enjoy painting.;I am inside paint.;I dislike painting.~0~“Be into” means to be interested in something.|Which is a polite invitation?~Would you like to join us?;You join us now.;Why not joined us?~0~“Would you like” offers a choice politely.|What hobby have you kept or recently tried? Why?|Explain your hobby to a beginner, answer their questions, and invite them to a suitable first session.
Express food preferences and make recommendations|Preferences with “prefer” and “would rather”|Use “I prefer tea to coffee” for a general preference and “I’d rather have tea” for a choice now. State allergies or dietary needs clearly rather than as a casual dislike.|A: What should I try here? / B: The vegetable noodles are excellent. Do you like spicy food? / A: A little, but I can’t eat peanuts. / B: Let’s check the ingredients before ordering.|When recommending food, ask about restrictions first and describe taste, texture, or spice level.|Which sentence describes a general preference?~I prefer tea to coffee.;I rather tea than coffee.;I prefer tea than coffee.~0~Use “prefer X to Y.”|How should you clearly state a food restriction?~I can't eat peanuts.;Peanuts are not my favorite.;Maybe peanuts no.~0~Direct wording avoids misunderstandings.|Describe a favorite meal with two taste words and one reason you enjoy it.|Recommend a dish to a visitor, check for dietary needs, and suggest an alternative.
Order politely and confirm details|Could I / Can I for requests; without and with|“Could I get a small coffee?” is polite. “Without milk” removes an ingredient; “with oat milk” specifies a replacement. Repeat the final order if anything is unclear.|A: Hi, could I get an iced latte with oat milk? / B: Of course. What size would you like? / A: Small, please. And a cheese sandwich for here. / B: One small iced latte with oat milk and one sandwich. Anything else?|“For here” means you will eat or drink at the cafe; “to go” means you will take it away.|Which request is both clear and polite?~Could I get a small tea, please?;Give tea.;I need tea you.~0~“Could I” and “please” soften the request.|What does “to go” mean?~Take it away.;Eat it inside.;Pay later.~0~“To go” describes takeaway service.|Order two items, modify one, and specify for here or to go.|You are the customer; a partner is the server. The server asks about size and repeats the order for confirmation.
Build a short conversation from familiar topics|Follow-up questions and natural transitions|Avoid a chain of unrelated questions. Respond to the other person first, then ask a question connected to their answer: “You mentioned hiking. Where do you usually go?”|A: How’s your week going? / B: Pretty well. I tried a new cafe yesterday. / A: That sounds nice. What did you order? / B: A chai latte. They also had excellent pastries. / A: Speaking of food, have you tried the bakery near the station?|A natural conversation shares turns. Answer questions with a little detail so your partner has something to ask about.|Which response encourages more conversation?~That sounds interesting. How did it go?;Okay.;Next subject.~0~It acknowledges and asks a connected question.|Choose a connected follow-up to “I started running.”~Where do you usually run?;What color is your phone?;Do you know the time?~0~Ask about the activity just mentioned.|Which topic from Days 1–6 was easiest? Which needs more practice?|Hold a five-minute conversation that includes at least three earlier topics and four follow-up questions.
Describe weather and adjust plans|It is + adjective; conditional “if”|Say “It’s sunny,” “It’s raining,” or “It’s been chilly lately.” For a possible future event, use “If it rains, we can go inside,” not “If it will rain.”|A: What’s the forecast for Saturday? / B: It looks cloudy, with a chance of rain. / A: Shall we still go to the park? / B: Let’s decide in the morning. If it rains, we can visit the museum.|Weather is useful small talk, but connect it to a preference or plan to make the exchange richer.|Which sentence is natural?~If it rains, we can go inside.;If it will rain, we can inside.;If raining, go can.~0~Use present tense after “if” for this future possibility.|Which phrase describes recent weather?~It's been windy lately.;It windy has lately.;Wind lately be.~0~“It’s been” connects past days to now.|Describe today's weather and how it affects your plans.|Plan an outdoor outing with a backup indoor option.
Describe your neighborhood to a newcomer|There is/are; distance expressions|“There’s a library nearby” introduces a place. “It’s within walking distance” means you can reasonably walk there. Describe both atmosphere and practical features.|A: What’s your neighborhood like? / B: It’s lively but fairly quiet at night. There’s a park and a small market nearby. / A: Is it easy to get around? / B: Yes. The train station is within walking distance.|Local recommendations are more useful when you mention who the place is good for and when to go.|Which phrase says a place is nearby on foot?~Within walking distance;Beyond walking ideas;Under distance foot~0~This is the conventional distance phrase.|Choose the correct introduction to one place.~There's a park nearby.;There are a park nearby.;There have park nearby.~0~Use “there is” with a singular noun.|What are two places a visitor should know in your area?|Introduce your neighborhood to someone moving in; recommend a place to eat and a way to travel.
Give and check directions|Imperatives and sequencing|Use short steps: “Go straight,” “Turn left at the lights,” “It’s next to the bank.” Check understanding with “So I turn right after the bridge?”|A: Excuse me, how do I get to the library? / B: Go straight for two blocks, then turn right at the traffic lights. / A: Is it on the left? / B: Yes, just past the pharmacy.|Landmarks such as stations and shops can be easier to follow than street names alone.|What comes after “turn right at”?~The traffic lights;To traffic lights;Traffic lights on~0~“At” introduces the point where you turn.|Which sentence checks understanding?~So I take the next left?;You not right?;Where you say again all?~0~Restating a step lets the speaker confirm it.|Give directions from your home to a nearby shop using three steps.|A visitor asks for a station; give directions and have them repeat the route back.
Compare and choose an item in a store|Comparatives and polite requests|Use “This one is cheaper than that one” and “It fits better.” Asking “Can I try it on?” is appropriate for clothing; “Can I see it?” works for other items.|A: Do you have this jacket in a medium? / B: Let me check. Here you are. / A: Thanks. Can I try it on? / B: Of course. The fitting room is over there. / A: This size fits better. How much is it?|“I’ll think about it” politely leaves a decision open without promising to buy.|Which sentence compares two prices?~This one is cheaper than that one.;This one cheaper that one.;This one more cheap from that.~0~Use comparative “cheaper than.”|What do you say before trying on a jacket?~Can I try it on?;Can I put it?;Could it try me?~0~“Try it on” is the clothing expression.|Compare two things you might buy by price, comfort, and quality.|Role-play asking for another size, trying it on, and deciding whether to buy.
Agree on a specific plan|Invitations, alternatives, and confirmation|A plan is complete when both people know the day, time, place, and activity. If a suggestion does not work, offer an alternative: “I can’t do Friday. How about Saturday?”|A: Are you free on Saturday afternoon? / B: I think so. What did you have in mind? / A: Coffee around three? / B: That works. Let’s meet outside the station at 2:45 and walk over.|“That works for me” accepts a suggestion. Repeat the final details to prevent confusion.|Which reply proposes an alternative?~Friday doesn't work. How about Sunday?;No.;Sunday maybe is no.~0~A clear alternative keeps planning moving.|What information makes a meeting plan complete?~Day, time, place, and activity;Only the day;Only the activity~0~Both people need the practical details.|Invite someone to an activity and offer a backup time.|Plan a weekend outing; your partner is unavailable at your first suggested time.
Explain work or study in plain language|Present continuous for current projects|“I work in design” describes your field; “I’m working on a new website” describes a current project. If a job title is unfamiliar, explain what you actually do.|A: What are you working on these days? / B: I’m studying biology and preparing a presentation about local rivers. / A: That sounds interesting. What’s the hardest part? / B: Finding reliable data and explaining it simply.|When someone asks about your work, adjust detail to their interest instead of listing every responsibility.|Which describes a current project?~I'm working on a presentation.;I work on presentation yesterday.;I am work presentation.~0~Present continuous suits work in progress.|Which question invites more detail?~What's the hardest part?;Work yes?;You done?~0~It asks about the person's experience.|Explain a task you do regularly and a project you are doing now.|Describe a project to someone outside your field; invite and answer a clarifying question.
Tell a short story in order|Past tense and sequencing markers|Anchor the listener: when and where did it happen? Then use “At first,” “Then,” and “In the end.” End with why the event mattered, not only what happened.|A: Did anything interesting happen this week? / B: Yes. On Tuesday, I missed my usual bus. At first, I was frustrated. / A: What happened next? / B: I walked a different route, found a new bakery, and arrived on time after all.|Pause between events; listeners can ask “What happened next?” or “How did you feel?”|Which phrase signals the conclusion?~In the end;At first;Before that~0~“In the end” introduces the outcome.|What should a clear story establish near the start?~When and where it happened;Every small detail;The final opinion only~0~Context helps the listener follow events.|Tell a story about a small surprise this week, including your reaction.|Tell a two-minute story while a partner asks two follow-up questions.
Discuss travel memories and wishes|Present perfect for experience; past simple for details|“I’ve been to Kyoto” states a life experience. “I went there in 2024” gives a finished time. Use “I’d love to visit” for a future wish.|A: Have you ever been to Portugal? / B: Yes, I went to Porto two years ago. / A: What was the best part? / B: Walking beside the river in the evening. I’d love to go back.|Ask about experiences without assuming everyone has the time or money to travel; local outings count too.|Which sentence mentions a finished time correctly?~I went there last year.;I've been there last year.;I have gone last year.~0~Use past simple with “last year.”|Which phrase expresses a wish?~I'd love to visit.;I went to visit yesterday.;I've visited in 2020.~0~“I’d love to” describes a desired future experience.|Describe a trip or local outing using one sensory detail.|Ask a partner about a memorable place and explain where you would like to go next.
Handle hotel check-in and requests|Reservation language and polite requests|“I have a reservation under [name]” lets staff find the booking. Ask specific questions about check-in, breakfast, Wi-Fi, or a room issue, one at a time.|A: Hello, I have a reservation under Lee. / B: Welcome. May I see your ID? / A: Of course. Is breakfast included? / B: Yes, from seven to ten. / A: Great. Could I get an extra towel, please?|Check the answer you receive: “So breakfast starts at seven?” can confirm an important detail.|How do you identify a booking?~I have a reservation under Lee.;I book as Lee thing.;My booking is under to Lee.~0~“Under” introduces the reservation name.|Which request is polite?~Could I get an extra towel, please?;Give extra towel now.;I must towel extra.~0~“Could I” frames a courteous request.|Ask about check-in time and one included service.|Check into a hotel, confirm a booking, ask two questions, and request an extra item.
Describe a minor health issue and show care|Symptoms with “have” and duration with “since/for”|Say “I have a headache,” “I feel tired,” and “I’ve had a headache since morning.” “Since” names a starting point; “for” names a length of time.|A: You look tired. Are you okay? / B: I have a headache. I’ve felt unwell since this morning. / A: I’m sorry to hear that. Do you need a break? / B: Yes, I think I’ll rest for a while.|Avoid making assumptions about someone’s health. Ask what support they would find helpful.|Which phrase gives a starting point?~Since this morning;For this morning;At two hours~0~“Since” goes with a starting time.|Which response shows care?~I'm sorry to hear that. Do you need a break?;You are wrong sick.;Forget it.~0~Acknowledgment plus an offer is supportive.|Describe a minor symptom and when it started, without giving medical advice.|A colleague feels unwell. Ask how they are, offer practical help, and respect their answer.
Talk about movement and realistic goals|Frequency, ability, and gradual change|Use “I go for a walk three times a week” for frequency and “I’m trying to build up to 30 minutes” for a goal. “Let’s take it easy” suggests a comfortable pace.|A: How do you stay active? / B: I walk after lunch when I can. I’m trying to be more consistent. / A: Would you like to go together tomorrow? / B: Sure, but let’s take it easy. I’m just getting started.|Different bodies and schedules need different routines; frame your own preferences without judging others.|Which phrase describes frequency?~Three times a week;At three weeks;In week three times~0~“Times a week” says how often.|What does “take it easy” suggest?~Use a comfortable pace.;Go as fast as possible.;Stop talking.~0~It asks for less intensity.|What physical activity feels enjoyable or manageable to you?|Compare two activities and invite a friend to try an easy session.
Recommend entertainment without spoiling it|Descriptions and opinions with reasons|Give a short premise, then why you liked it: “It’s about two friends on a trip. I liked the dialogue.” Ask about taste before recommending a genre.|A: Have you watched anything good lately? / B: I saw a mystery film called The Last Window. It's about a missing painting. / A: Was it scary? / B: Not really. It was clever and funny. I think you'd like it.|A recommendation works best when it matches the listener’s interests; avoid revealing the ending.|Which sentence gives a reason?~I enjoyed it because the characters felt real.;I enjoyed it.;It enjoyed me because.~0~“Because” links an opinion to evidence.|Which question checks taste before recommending?~Do you like mysteries?;Have you seen my ticket?;When is the bus?~0~Ask about genre preference.|Recommend a book, film, song, or show with a premise and two reasons.|Ask about a partner's taste, then give a spoiler-free recommendation.
Explain a tool and troubleshoot gently|Instructions with sequence; “have you tried”|Give one step at a time: “First, open settings. Then, choose notifications.” “Have you tried restarting it?” is a gentle suggestion, not a guarantee.|A: I'm having trouble with this app. It won't save my notes. / B: Have you checked your connection? / A: Yes, that seems fine. / B: Let's try closing and reopening the app. If that doesn't work, we can check the storage settings.|When explaining an app, avoid unexplained technical terms and ask whether the person can see the same screen.|Which is a gentle troubleshooting suggestion?~Have you tried restarting it?;Restart now, obviously.;It never works.~0~The question offers a possible step politely.|Which phrase signals the next instruction?~Then, choose settings.;Yesterday settings.;Maybe thing setting.~0~“Then” sequences the action.|Explain how to do one useful thing in an app, in three steps.|Help a friend solve a simple app problem; check after each step whether it worked.
Give opinions and disagree politely|Opinion + reason + acknowledgment|State your view (“I prefer printed books”), add a reason (“because I can focus better”), and acknowledge another perspective (“I see why you like ebooks”). Disagreement can stay friendly.|A: I think ebooks are more convenient. / B: I see your point. I prefer paper books because I spend less time on a screen. / A: That's fair. What kind of books do you read? / B: Mostly novels. What about you?|Ask “What makes you say that?” to understand a view, not to challenge someone aggressively.|Which reply disagrees politely?~I see your point, but I prefer paper books.;You are wrong.;No, bad idea always.~0~Acknowledge before giving your view.|What makes an opinion easier to discuss?~A clear reason and a question;A louder voice;A repeated claim~0~Reasons and curiosity support conversation.|Choose two apps or activities; say which you prefer and why.|Discuss two familiar choices; each person gives a reason and acknowledges the other view.
Explain a celebration or tradition|Customs with “usually” and “It's a tradition to”|Describe what happens, when, and why it matters. “We usually cook together” is a custom; “It means a chance to reconnect” gives its significance.|A: Do you have a favorite celebration? / B: Yes. Every spring, my relatives cook together and share stories. / A: What does the day mean to you? / B: It’s a chance to spend time with people I don’t see often.|Ask open questions and allow others to describe their own traditions instead of assuming shared customs.|Which question asks about meaning?~What does it mean to you?;What time is it?;Do I own it?~0~It invites a personal explanation.|Which phrase describes a recurring custom?~We usually cook together.;We cooking yesterday.;We will used cook.~0~“Usually” marks a repeated practice.|Describe a tradition in your family, community, or friend group.|Explain a celebration to a visitor and ask about one important to them.
Reflect on a past change|“Used to” for old habits; past events and present results|“I used to be nervous speaking English” describes a past state that may have changed. “Since then, I’ve practiced weekly” connects a past turning point to now.|A: How did you learn to cook? / B: I used to rely on simple meals. Then a friend showed me a few recipes. / A: What changed after that? / B: Since then, I've cooked dinner for myself most evenings.|A good personal story names a challenge, one action you took, and what you learned.|Which describes a past habit that changed?~I used to avoid speaking in groups.;I use to avoided groups.;I am used avoid groups.~0~“Used to” takes a base verb.|Which phrase links a change to the present?~Since then, I've practiced regularly.;Yesterday, I practicing.;Before then tomorrow.~0~“Since then” marks continuing change.|What is a skill you learned through practice? What was hard at first?|Tell a before-and-after story about learning a skill; answer what helped most.
Talk about goals without overpromising|Plans, hopes, and concrete next steps|“I’m planning to…” suggests an intention; “I hope to…” states a wish. Make a goal actionable by naming a next step and a time: “This weekend, I’ll research a class.”|A: What are you looking forward to this year? / B: I’m hoping to speak more confidently. / A: How will you start? / B: I’ll practice for ten minutes after dinner three days a week.|A partner can help by asking about obstacles and encouragement, not by judging the ambition of the goal.|Which is a concrete next step?~I'll practice ten minutes on Monday.;I will be better someday.;Success will happen.~0~It names an action and time.|Which phrase states a hope?~I hope to visit my cousin.;I hoped visit next now.;I am hope visiting.~0~“Hope to” takes the base verb.|Name one small goal and the first action you can take this week.|Ask a partner about a goal, help them make a next step specific, and share your own.
Describe a problem and agree on a solution|Issue, impact, suggestion, agreement|Keep the problem factual: “The package arrived late, so I missed the event.” Suggest an option and ask whether it works. Repeat the final agreement.|A: The meeting room is booked at our usual time. / B: Could we move the meeting to three? / A: I have another call then. How about four? / B: Four works. I'll update the invitation.|Distinguish the problem from blame; a calm description makes it easier to solve together.|Which phrase proposes a solution?~Could we try a different time?;This is your fault.;Nothing can happen.~0~“Could we” offers a collaborative option.|What should you do after agreeing on a solution?~Confirm the action and time.;Change the subject.;Repeat the complaint.~0~Shared details prevent a second problem.|Describe a small scheduling problem and suggest two ways to fix it.|A delivery or meeting changes unexpectedly; explain the effect and agree on a practical fix.
Make a polite service complaint|Specific issue, desired remedy, appreciation|State what you expected and what happened: “I ordered the blue shirt, but received the green one.” Then ask clearly for an exchange, refund, or correction as appropriate.|A: Hi, I'm afraid there's a problem with my order. I received the wrong size. / B: I'm sorry about that. What size did you order? / A: Medium, but this is small. Could you help me exchange it? / B: Certainly. Let me check availability.|Politeness does not require accepting an unsolved problem; you can repeat the specific remedy you need.|Which complaint gives useful detail?~I ordered a medium, but received a small.;It's bad.;Everything wrong always.~0~Specific facts make a fix possible.|Which request asks for a remedy?~Could you help me exchange it?;Why things?;I am angry now.~0~It asks for the action you want.|Write or say a clear complaint about a harmless wrong order.|Role-play customer and employee; describe the mismatch and agree on an exchange or correction.
Offer advice while respecting choice|Could, might, and “If I were you”|“You could try shorter sessions” leaves room for choice. “If I were you, I’d…” presents your perspective, not an order. Ask what the person has already tried.|A: I want to speak more English, but I'm busy. / B: That sounds frustrating. Have you considered five-minute voice notes? / A: I could do that on my commute. / B: It might be worth trying for a week. See how it feels.|Good advice begins by listening and ends by leaving the decision with the other person.|Which suggestion leaves room for choice?~You could try a shorter session.;You must do this.;Never do that again.~0~“Could” offers an option.|Which question helps before advising?~What have you tried so far?;Why are you always wrong?;Do you obey me?~0~Learning context makes advice relevant.|A friend struggles to make time for practice. Suggest two small options.|Listen to a partner's problem, ask one question, and offer gentle advice without insisting.
Sustain a longer chat and repair misunderstandings|Transitions and clarification strategies|Use “That reminds me…” to connect topics and “By the way…” to introduce a new one. When you do not understand, ask “What do you mean by…?”; when they do not, say “Let me put it another way.”|A: I tried a new restaurant yesterday. / B: That reminds me: did you ever visit the food market? / A: Not yet. Is it near the station? / B: Yes, two streets away. / A: Sorry, do you mean the north or south station? / B: The south one. Let me put it another way: it's next to the museum.|Clarification is normal, even for fluent speakers. Restating an idea is a valuable conversation skill.|Which phrase requests clarification?~What do you mean by “nearby”?;Yes everything.;Maybe I agree.~0~It asks for a clearer meaning.|Which phrase smoothly changes subject?~By the way, have you seen the new cafe?;New subject immediately.;Stop this topic.~0~“By the way” introduces a related or new thought.|Which phrase helps you recover when someone is confused?|Talk for ten minutes across three topics, use a transition, and clarify at least one detail.
Discuss a local event with curiosity|Source, fact, uncertainty, and opinion|“I heard about the new community garden” states what you encountered. “From what I understand…” signals a tentative summary. Distinguish what is confirmed from what you think about it.|A: I heard the library is hosting evening language exchanges. / B: That sounds useful. Do you know when they start? / A: I'm not sure. From what I understand, the first one is next month. / B: Let's check the library's announcement before making plans.|If you do not know enough, saying “I haven't looked into it enough yet” is more credible than guessing.|Which phrase signals uncertainty honestly?~From what I understand, it starts next month.;It definitely starts tomorrow, I guess.;Everybody knows the date.~0~It frames a tentative account.|What is the best next step before sharing an event date?~Check the organizer's announcement.;Guess from memory.;Repeat a rumor.~0~The organizer can confirm the details.|Describe a community event and separate one fact from one opinion.|Discuss a local event; ask for a source, express interest, and acknowledge uncertainty.
Combine skills and choose your next practice cycle|Review, self-correction, and next steps|Use familiar phrases flexibly rather than memorizing a perfect speech. In a long conversation, vary questions, give reasons, tell one story, and repair any misunderstanding.|A: What did you enjoy most about this month? / B: I feel more comfortable asking follow-up questions. / A: What would you like to improve next? / B: I still pause when telling stories, so I'll practice one short story every week.|Judge progress by what you can communicate, not only by grammatical accuracy. Note one strength and one next step.|Which goal is specific and repeatable?~Tell one short story every week.;Speak perfectly forever.;Never pause again.~0~A weekly action is practical.|Which response keeps a conversation moving?~That reminds me of a trip I took. What about you?;Yes.;Finished.~0~It adds detail and returns a question.|Which three phrases now feel natural? What two skills need attention?|Hold a 15-minute conversation covering four topics. Record it, review it, and set two goals for next month.
'''.strip().splitlines()
assert len(raw)==30,len(raw)
lessons=[]
for i,(section,line) in enumerate(zip(sections,raw),1):
    fields=line.split('|')
    assert len(fields)==9,(i,len(fields))
    title=re.search(r'DAY \d+ - (.+)',section).group(1)
    theme=re.search(r'Theme: (.+)',section).group(1)
    phrases=re.search(r'Important phrases: (.+)',section).group(1).split('; ')
    def question(q):
        stem,opts,answer,explanation=q.split('~')
        return dict(stem=stem,options=opts.split(';'),answer=int(answer),explanation=explanation)
    qs=[question(fields[5]),question(fields[6])]
    for j,q in enumerate(qs):
        shift=(i+j)%3
        q['options']=q['options'][shift:]+q['options'][:shift]
        q['answer']=(q['answer']-shift)%3
    extra=enrich(i)
    lesson=dict(day=i,title=title,theme=theme,objective=fields[0],focus=fields[1],teaching=fields[2],dialogue=[v.strip() for v in fields[3].split(' / ')],usage=fields[4],phrases=phrases,phraseFamilies=extra['phraseFamilies'],extraDialogues=extra['extraDialogues'],quiz=qs+extra['extraQuiz'],reflection=fields[7],roleplay=fields[8],discussion=extra['discussion'])
    lessons.append(lesson)
(root/'lessons.json').write_text(json.dumps(lessons,ensure_ascii=False,indent=2)+'\n')
book=['# 30-Day Conversational English Coursebook','', 'A self-paced month of daily spoken English practice. Each day is designed for about 25–35 minutes: 3 minutes to recall, 10 minutes to learn from three conversations and phrase alternatives, 5 minutes for questions, 10–15 minutes for speaking, and 2 minutes to reflect. Study with a partner or speak both parts aloud. On review days, allow 10 extra minutes.','','## Daily routine','','1. **Recall:** Say yesterday’s useful phrases without looking. On Day 1, simply introduce yourself.','2. **Learn:** Read the theme, focus, teaching note, phrase families, and three model conversations. Repeat each exchange aloud twice, changing one detail to fit your life.','3. **Check:** Answer the four multiple-choice questions before reading the answer key. Say the correct answer in a full sentence.','4. **Speak and reflect:** Do the role-play, answer at least two open prompts, and record one phrase to use again tomorrow.','','You can repeat any day. There is no requirement to complete lessons on consecutive calendar days. The website keeps an optional start date and saves progress in this browser.','','---','']
for l in lessons:
    book += [f"## Day {l['day']}: {l['title']}",'',f"**Theme:** {l['theme']}",f"**Goal:** {l['objective']}",f"**Language focus:** {l['focus']}",'',f"### Learn",'',l['teaching'],'',f"**Useful phrases**",'']
    book += [f"- {p}" for p in l['phrases']]
    book += ['', '**Ways to say it: choose a phrase that fits your situation**','']
    for family in l['phraseFamilies']:
        book += [f"**{family['label']}**",'']+[f"- {p}" for p in family['options']]+['']
    book += ['**Model conversation 1: Everyday example**','']+[f"{d}" for d in l['dialogue']]+['']
    for j,scene in enumerate(l['extraDialogues'],2):
        book += [f"**Model conversation {j}: {scene['label']}**",'']+scene['lines']+['']
    book += [f"**Conversation note:** {l['usage']}",'','### Practice questions','']
    for n,q in enumerate(l['quiz'],1):
        book += [f"{n}. {q['stem']}"]+[f"   - {chr(65+j)}. {o}" for j,o in enumerate(q['options'])]+['']
    book += [f"5. Open response: {l['reflection']}",'',f"6. {l['discussion'][0]}",'',f"7. {l['discussion'][1]}",'',f"8. Role-play: {l['roleplay']}",'','**Answer key**','']
    for n,q in enumerate(l['quiz'],1): book += [f"{n}. {chr(65+q['answer'])}. {q['options'][q['answer']]} — {q['explanation']}"]
    book += ['', '**After speaking:** What did you express clearly? Which phrase will you reuse tomorrow?','','---','']
(root/'COURSEBOOK.md').write_text('\n'.join(book)+'\n')
print("Generated",len(lessons),"lessons,",sum(len(l["quiz"]) for l in lessons),"scored questions,",len("\n".join(book).split()),"coursebook words")
